apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  ports:
  - port: 27017
    name: "mongo-port"
    targetPort: 27017
    nodePort: 32017
  selector:
    app: mongo
  type: NodePort
