apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-db-mongo-0
spec:
  storageClassName: local
  resources:
    requests:
      storage: 500Mi 
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: mongo

