apiVersion: v1
kind: Pod 
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo 
  volumes:
    - name: data-db
      persistentVolumeClaim:
        claimName: mongo-data-db
  containers:
    - name: mongo
      image: mongo:3.6
      volumeMounts:
        - name: data-db
          mountPath: /data/db

