apiVersion: v1
kind: Pod 
metadata:
  name: mongo
spec:
  nodeName: k8s-node2
  volumes:
    - name: mongo-data-db
      persistentVolumeClaim:
        claimName: mongo-data-db-mongo-0
  containers:
    - name: mongo
      image: mongo:3.6
      volumeMounts:
        - name: mongo-data-db
          mountPath: /data/db
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: number
            operator: In
            values:
            - two

