apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-db
  labels:
    app: mongo
spec:
  storageClassName: local
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/mongodb
            operator: In
            values: ['data']
