apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo-service"
  selector:
    matchLabels:
      app: mongo 
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.6
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-data-db
          mountPath: /home/eli.harper/data/mongodb
  volumeClaimTemplates:
    - metadata:
        name: mongo-data-db
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: 'local'
        resources:
          requests:
            storage: 500Mi

