apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-db
  labels:
    app: mongo
spec:
  storageClassName: local
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /home/eli.harper/data/mongodb
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node2
