apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    metallb.universe.tf/address-pool: light-controller-LB-pool
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 32241
  selector:
    app: api
  type: LoadBalancer 
  loadBalancerIP: 192.168.1.92
