apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: number
                operator: In
                values:
                - one

      containers:
      - image: eliharper/lights_api:7.28.3
        name: api
        ports:
        - containerPort: 5001
