apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30303
  selector:
    app: web
  type: LoadBalancer 
