apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: eliharper/lights_ui:7.28.13
        name: web
        ports:
        - containerPort: 8080
      restartPolicy: Always
